### ISSUE TITLE
module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell

### ISSUE THREAD

**Issue by nashid** [tensorflow/nmt#466]
Code does not work with the latest Tensorflow library:

```
Traceback (most recent call last):
  File "/Users/XXXXX/opt/anaconda2/envs/XXXXXX/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/XXXXX/opt/anaconda2/envs/XXXXXX/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXX/Model/nmt/nmt.py", line 28, in <module>
    from . import inference
  File "/Users/XXXXX/Model/nmt/inference.py", line 25, in <module>
    from . import gnmt_model
  File "/Users/XXXXX/Model/nmt/gnmt_model.py", line 216, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'
```

**Comment by bjjoy** [comment]
I have the same problem in tf 2.2.0. I change tf version to 1.14，problem has been solved

**Comment by bjjoy** [comment]
> Code does not work with the latest Tensorflow library:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/XXXXX/opt/anaconda2/envs/XXXXXX/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/XXXXX/opt/anaconda2/envs/XXXXXX/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/XXXXX/Model/nmt/nmt.py", line 28, in <module>
>     from . import inference
>   File "/Users/XXXXX/Model/nmt/inference.py", line 25, in <module>
>     from . import gnmt_model
>   File "/Users/XXXXX/Model/nmt/gnmt_model.py", line 216, in <module>
>     class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
> AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'
> ```

I have the same problem in tf 2.2.0. I change tf version to 1.14，problem has been solved

**Comment by nashid** [comment]
@bjjoy so you have to install tensorflow 1.14?

I tried with tensorflow 1.5 which worked fine as well.

**Comment by parikshit-ai** [comment]
Its not working with 2.1.x, I am using rasa which requires >=2.1 & <2.2 so can anyone tell me what is the concrete solution??

**Comment by nashid** [comment]
@parikshit-ai I presume you meant its not working with 2.1.x?

If you found a solution, do keep us posted.

**Comment by bjjoy** [comment]
> @bjjoy so you have to install tensorflow 1.14?
> 
> I tried with tensorflow 1.5 which worked fine as well.

It should be 1.14==1.4. pip list to show tf version 1.14

**Comment by luozhouyang** [comment]
This code is not for tensorflow 2.x. tensorflow 2.x has many break changes.

**Comment by ArashHosseini** [comment]
@nashid you can use it with [nvidia](https://github.com/NVIDIA/tensorflow) tf. i am using without any problem.
